# Generated by Django 5.1.1 on 2024-09-24 02:35

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/users/')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profiles',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Trip_per_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_reserve_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('username', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='username')),
            ],
        ),
    ]
