# Generated by Django 5.1.1 on 2024-09-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='h_photo1',
            field=models.ImageField(blank=True, null=True, upload_to='images/reserve/hotels', verbose_name='hotel photo 1'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='h_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/reserve/hotels', verbose_name='hotel photo 2'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='h_photo3',
            field=models.ImageField(blank=True, null=True, upload_to='images/reserve/hotels', verbose_name='hotel photo 3'),
        ),
    ]
