# Generated by Django 5.1.1 on 2024-09-24 02:35

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_features',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trips.trips', verbose_name='name')),
                ('img1', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='Trip photo 1')),
                ('img2', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='Trip photo 2')),
                ('img3', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='Trip photo 3')),
                ('img4', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/Users/User/Desktop/UNIVERSITY/React project/myapp/public'), upload_to='images/reserve', verbose_name='Trip photo 4')),
                ('access_plane_1', models.BooleanField(default=False, verbose_name=' access point 1 by plane')),
                ('access_plane_name_1', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_plane_price_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('plane_start_at_1', models.DateTimeField(blank=True, null=True)),
                ('access_plane_2', models.BooleanField(default=False, verbose_name=' access point 2 by plane')),
                ('access_plane_name_2', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_plane_price_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('plane_start_at_2', models.DateTimeField(blank=True, null=True)),
                ('access_plane_3', models.BooleanField(default=False, verbose_name=' access point 3 by plane')),
                ('access_plane_name_3', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_plane_price_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('plane_start_at_3', models.DateTimeField(blank=True, null=True)),
                ('access_plane_4', models.BooleanField(default=False, verbose_name=' access point 4 by plane')),
                ('access_plane_name_4', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_plane_price_4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('plane_start_at_4', models.DateTimeField(blank=True, null=True)),
                ('access_plane_5', models.BooleanField(default=False, verbose_name=' access point 5 by plane')),
                ('access_plane_name_5', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_plane_price_5', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('plane_start_at_5', models.DateTimeField(blank=True, null=True)),
                ('access_bus_1', models.BooleanField(default=False, verbose_name=' access point 1 by bus')),
                ('access_bus_name_1', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_bus_price_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('bus_start_at_1', models.DateTimeField(blank=True, null=True)),
                ('access_bus_2', models.BooleanField(default=False, verbose_name=' access point 2 by bus')),
                ('access_bus_name_2', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_bus_price_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('bus_start_at_2', models.DateTimeField(blank=True, null=True)),
                ('access_bus_3', models.BooleanField(default=False, verbose_name=' access point 3 by bus')),
                ('access_bus_name_3', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_bus_price_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('bus_start_at_3', models.DateTimeField(blank=True, null=True)),
                ('access_bus_4', models.BooleanField(default=False, verbose_name=' access point 4 by bus')),
                ('access_bus_name_4', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_bus_price_4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('bus_start_at_4', models.DateTimeField(blank=True, null=True)),
                ('access_bus_5', models.BooleanField(default=False, verbose_name=' access point 5 by bus')),
                ('access_bus_name_5', models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='name')),
                ('access_bus_price_5', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='price')),
                ('bus_start_at_5', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
