# Generated by Django 5.1.1 on 2024-09-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Trip photo'),
        ),
    ]
