# Generated by Django 5.1.1 on 2024-09-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trips_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Trip photo'),
        ),
    ]
